/*
 JavaScript tracking client

 @source https://github.com/piwik/piwik/blob/master/js/piwik.js
 @license https://opensource.org/licenses/BSD-3-Clause BSD-3 Clause (also in js/LICENSE.txt)
 @license magnet:?xt=urn:btih:c80d50af7d3db9be66a4d0a86db0286e4fd33292&dn=bsd-3-clause.txt BSD-3-Clause
*/
(function(){function O(a){"@babel/helpers - typeof";return O="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"==typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c},O(a)}function I(a){console.error(a)}function fd(){if(dc)return Va.exports;dc=1;(function(a,c){(function(e,g){a.exports=g()})(gd,function(){function e(q){return q.charAt(0).toUpperCase()+q.substring(1)}function g(q){return function(){return this[q]}}
function h(q){if(q)for(var r=0;r<u.length;r++)if(void 0!==q[u[r]])this["set"+e(u[r])](q[u[r]])}var n=["isConstructor","isEval","isNative","isToplevel"],m=["columnNumber","lineNumber"],p=["fileName","functionName","source"],u=n.concat(m,p,["args"],["evalOrigin"]);h.prototype={getArgs:function(){return this.args},setArgs:function(q){if("[object Array]"!==Object.prototype.toString.call(q))throw new TypeError("Args must be an Array");this.args=q},getEvalOrigin:function(){return this.evalOrigin},setEvalOrigin:function(q){if(q instanceof
h)this.evalOrigin=q;else if(q instanceof Object)this.evalOrigin=new h(q);else throw new TypeError("Eval Origin must be an Object or StackFrame");},toString:function(){var q=this.getFileName()||"",r=this.getLineNumber()||"",F=this.getColumnNumber()||"",K=this.getFunctionName()||"";return this.getIsEval()?q?"[eval] ("+q+":"+r+":"+F+")":"[eval]:"+r+":"+F:K?K+" ("+q+":"+r+":"+F+")":q+":"+r+":"+F}};h.fromString=function(q){var r=q.indexOf("("),F=q.lastIndexOf(")"),K=q.substring(0,r);r=q.substring(r+1,
F).split(",");q=q.substring(F+1);if(0===q.indexOf("@")){var J=/@(.+?)(?::(\d+))?(?::(\d+))?$/.exec(q,""),U=J[1],H=J[2];J=J[3]}return new h({functionName:K,args:r||void 0,fileName:U,lineNumber:H||void 0,columnNumber:J||void 0})};for(var v=0;v<n.length;v++)h.prototype["get"+e(n[v])]=g(n[v]),h.prototype["set"+e(n[v])]=function(q){return function(r){this[q]=!!r}}(n[v]);for(n=0;n<m.length;n++)h.prototype["get"+e(m[n])]=g(m[n]),h.prototype["set"+e(m[n])]=function(q){return function(r){if(isNaN(parseFloat(r))||
!isFinite(r))throw new TypeError(q+" must be a Number");this[q]=Number(r)}}(m[n]);for(m=0;m<p.length;m++)h.prototype["get"+e(p[m])]=g(p[m]),h.prototype["set"+e(p[m])]=function(q){return function(r){this[q]=String(r)}}(p[m]);return h})})(Va);return Va.exports}function La(a){var c=/^(?:(?:https?|ftp):)\/*(?:[^@?]+@)?([^:/#]+)/.exec(a);return c?c[1]:a}function ec(a){var c=document.createElement("a");c.href=a;return{href:c.href,hostname:c.hostname,pathname:c.pathname}}function fc(a,c){a=String(a);if(-1===
a.indexOf("?"+c+"=")&&-1===a.indexOf("&"+c+"="))return a;var e=a.indexOf("?");if(-1===e)return a;var g=a.substr(e+1);e=a.substr(0,e);if(g){var h="",n=g.indexOf("#");-1!==n&&(h=g.substr(n+1),g=g.substr(0,n));n=g.split("&");for(var m=n.length-1;0<=m;m--)g=n[m].split("=")[0],g===c&&n.splice(m,1);(g=n.join("&"))&&(e=e+"?"+g);h&&(e+="#"+h)}return e}function gc(a){return(a=/^([a-z]+):/.exec(a))?a[1]:null}function rb(a,c){a=String(a).toLowerCase();c=String(c).toLowerCase();if(a===c)return!0;if("."===c.slice(0,
1)){if(a===c.slice(1))return!0;var e=a.length-c.length;if(0<e&&a.slice(e)===c)return!0}return!1}function Wa(a,c){var e=document.createElement("a");0!==a.indexOf("//")&&0!==a.indexOf("http")&&(0===a.indexOf("*")&&(a=a.substr(1)),0===a.indexOf(".")&&(a=a.substr(1)),a="http://"+a);e.href=c.toAbsoluteUrl(a);return e.pathname?e.pathname:""}function Xa(a,c){return c&&a&&0===String(a).indexOf(c)}function sb(a,c){var e=(new RegExp("[\\?&#]"+c+"=([^&#]*)")).exec(a);return e?decodeURIComponent(e[1]):""}function Ya(a,
c){a=fc(a,c.visitorIdUrlParameter);return c.discardHashTag?a.replace(/#.*/,""):a}function w(a){return"undefined"!==typeof a}function Ma(a){return"function"===typeof a}function wa(a){return"object"===O(a)}function R(a){return"string"===typeof a||a instanceof String}function qa(a){return"number"===typeof a||R(a)&&!isNaN(a)&&""!==a}function Na(a){var c=a.length;"."===a.charAt(--c)&&(a=a.slice(0,c));"*."===a.slice(0,2)&&(a=a.slice(1));-1!==a.indexOf("/")&&(a=a.substr(0,a.indexOf("/")));return a}function hd(a,
c,e){a||(a="");c||(c="");if("translate.googleusercontent.com"===a)""===e&&(e=c),c=sb(c,"u"),a=La(c);else if("cc.bingj.com"===a||"webcache.googleusercontent.com"===a||"74.6."===a.slice(0,5))c=document.links[0].href,a=La(c);return[a,c,e]}function Y(a,c){if(a&&a.indexOf)return a.indexOf(c);if(!w(a)||null===a||0===a.length)return-1;for(var e=0;e<a.length;){if(a[e]===c)return e;e++}return-1}function hc(a){if(a)return!w(a.children)&&w(a.childNodes)||w(a.children)?a.children:[]}function tb(a){var c;for(c=
a.parentNode;null!==c&&w(c)&&!t.isLinkElement(a);)a=c,c=a.parentNode;return a}function ub(a,c){a=String(a);return 0===a.lastIndexOf(c,0)}function xa(a,c){a=String(a);return-1!==a.indexOf(c,a.length-c.length)}function ic(a,c){c=String(c);a=String(a);return""!==a?a+c.charAt(0).toUpperCase()+c.slice(1):c}function jc(a,c){a=String(a);return a.substr(0,a.length-c)}function vb(a,c){var e="(^| )(piwik[_-]"+c;if(a)for(var g=0;g<a.length;g++)e+="|"+a[g];return new RegExp(e+")( |$)")}function id(a,c){var e=
t.getAttributeValueFromNode(a,"href");if(!e)return!1;var g=e.split("://");if(2!==g.length)return!1;e=g[0].toLowerCase();g=g[1];var h=g.indexOf("?");g=-1===h?g:g.slice(0,h);h=[];for(var n=0;n<c.length;n++){var m=c[n];jd.test(m)&&h.push(m)}for(n=0;n<h.length;n++){var p=h[n].split("://");if(2!==p.length)break;m=p[0].toLowerCase();p=p[1];if(e===m&&kc(g,p))return!0}return!1}function kc(a,c){ub(c,"/")||(c="/"+c);ub(a,"/")||(a="/"+a);if("/"===c||"/*"===c||a===c)return!0;c=String(c).toLowerCase();a=String(a).toLowerCase();
if(xa(c,"*"))return(c=c.slice(0,-1))&&"/"!==c&&a!==c?0===a.indexOf(c):!0;xa(a,"/")||(a+="/");xa(c,"/")||(c+="/");return 0===a.indexOf(c)}function lc(a,c,e,g){for(var h=0;h<e.length;h++){var n=Na(e[h]),m=Wa(e[h],g);if(rb(a,n)&&kc(c,m))return!0}return!1}function mc(a,c,e){a=tb(a);if(t.hasNodeAttribute(a,"href")&&w(a.href)){var g=t.getAttributeValueFromNode(a,"href");if(!Xa(g,e.configTrackerUrl)){var h=ec(g),n=h.pathname||Wa(g,c);g=h.hostname||La(h.href);var m=g.toLowerCase();h=h.href.replace(g,m);if(!/^(javascript|vbscript|jscript|mocha|livescript|ecmascript|mailto|tel|data|blob):/i.test(h)&&
(g=a.className,c=lc(m,n,e.configHostsAlias,c),a=t.hasNodeAttribute(a,"download"),Xa(h,e.configTrackerUrl)?e=0:(n=vb(e.configDownloadClasses,"download"),m=vb(e.configLinkClasses,"link"),e=new RegExp("\\.("+e.configDownloadExtensions.join("|")+")([?&#]|$)","i"),e=m.test(g)?"link":a||n.test(g)||e.test(h)?"download":c?0:"link"),e))return{type:e,href:h}}}}function kd(){var a=window.performance||window.mozPerformance||window.msPerformance||window.webkitPerformance;if(null!==a&&void 0!==a&&a.timing)return a.timing;
if(null!==a&&void 0!==a&&a.getEntriesByType)return a.getEntriesByType("navigation")[0]}function P(a,c,e){return 0<=c&&c<=e?"&"+a+"="+c:""}function Q(a,c){return Math.round(a[c]-(a.navigationStart||0))}function ld(a){var c="";a.unloadEventStart&&0!==a.unloadEventStart&&(c+=P("t_us",Q(a,"unloadEventStart"),65535));a.unloadEventEnd&&0!==a.unloadEventEnd&&(c+=P("t_ue",Q(a,"unloadEventEnd"),65535));a.redirectStart&&0!==a.redirectStart&&(c+=P("t_rs",Q(a,"redirectStart"),65535));a.redirectEnd&&0!==a.redirectEnd&&
(c+=P("t_re",Q(a,"redirectEnd"),65535));a.secureConnectionStart&&0!==a.secureConnectionStart&&(c+=P("t_ss",Q(a,"secureConnectionStart"),65535));a.fetchStart&&0!==a.fetchStart&&(c+=P("t_fs",Q(a,"fetchStart"),65535));a.domainLookupStart&&0!==a.domainLookupStart&&(c+=P("t_ds",Q(a,"domainLookupStart"),65535));a.connectStart&&0!==a.connectStart&&(c+=P("t_cs",Q(a,"connectStart"),65535));a.connectEnd&&0!==a.connectEnd&&(c+=P("t_ce",Q(a,"connectEnd"),65535));a.requestStart&&0!==a.requestStart&&(c+=P("t_qs",
Q(a,"requestStart"),65535));a.responseStart&&0!==a.responseStart&&(c+=P("t_as",Q(a,"responseStart"),65535));a.responseEnd&&0!==a.responseEnd&&(c+=P("t_ae",Q(a,"responseEnd"),65535));a.domLoading&&0!==a.domLoading&&(c+=P("t_dl",Q(a,"domLoading"),65535));a.domInteractive&&0!==a.domInteractive&&(c+=P("t_di",Q(a,"domInteractive"),16777215));a.domContentLoadedEventStart&&0!==a.domContentLoadedEventStart&&(c+=P("t_ls",Q(a,"domContentLoadedEventStart"),16777215));a.domContentLoadedEventEnd&&0!==a.domContentLoadedEventEnd&&
(c+=P("t_le",Q(a,"domContentLoadedEventEnd"),16777215));a.domComplete&&0!==a.domComplete&&(c+=P("t_dc",Q(a,"domComplete"),16777215));a.loadEventEnd&&0!==a.loadEventEnd&&(c+=P("t_ee",Q(a,"loadEventEnd"),16777215));return c}function md(a){var c,e="loading",g=void 0;if(null!==(c=navigator.userAgentData)&&void 0!==c&&c.getHighEntropyValues)navigator.userAgentData.getHighEntropyValues(["model","brands","platform","platformVersion","fullVersionList"]).then(function(h){g=h;e="available"})["catch"](function(){e=
"unavailable"})["finally"](function(){a.onResolve()});else e="unavailable";return{getState:function(){return"available"===e?{state:"available",hints:g}:{state:e}}}}function nc(a){if(!(a instanceof Array))return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' parameter if specified, has to be array of numbers. Received: '".concat(a,"'")};if(0===a.length)return{isValid:!1,error:"[enableHeartBeatTimer] - 'timers' cannot be empty array"};for(var c=0;c<a.length;c++)if("number"!==typeof a[c])return{isValid:!1,
error:"[enableHeartBeatTimer] - 'timers' array has to contain only numeric values. Received: '".concat(a,"'")};return{isValid:!0}}function nd(a){var c=!1,e=!1,g=!0,h=oc,n,m=0,p=function(){var q=h[m];n=void 0===q?void 0:setTimeout(function(){if(g)a.onPing(ra.PeriodicHeartbeat);m++;p()},1E3*q)},u=function(){e&&(p(),e=!1);g||(g=!0,a.onPing(ra.PeriodicHeartbeat))},v=function(){g=!1;a.onPing(ra.BlurHeartbeat)};return{enable:function(){c=!0;window.addEventListener("focus",u);window.addEventListener("blur",
v);document.hasFocus()?p():e=!0},disable:function(){e=c=!1;clearTimeout(n);n=void 0;m=0;window.removeEventListener("focus",u);window.removeEventListener("blur",v)},setTimings:function(q){var r=nc(q);if(!r.isValid)return I(r.error),this;h=q;return this},isEnabled:function(){return c}}}function od(){var a=[[/g/g,"10"],[/h/g,"11"],[/i/g,"12"],[/j/g,"13"],[/k/g,"14"],[/l/g,"15"],[/m/g,"16"],[/n/g,"17"],[/o/g,"18"],[/p/g,"19"],[/q/g,"1a"],[/r/g,"1b"],[/s/g,"1c"],[/t/g,"1d"],[/u/g,"1e"],[/v/g,"1f"],[/w/g,
"20"],[/x/g,"21"],[/y/g,"22"],[/z/g,"23"],[/_/g,"3e"],[/-/g,"3f"]],c=/^[0-9a-f]{16}$/;return function(e){if(e&&!c.test(e)){e=e.toLowerCase().substr(4,16);for(var g=0;g<a.length;g+=1)e=e.replace(a[g][0],a[g][1]);e=e.substr(0,16)}return e}}function pd(a){return{transformIfAMPCookie:od(),getCookieName:function(c){return a.getCookiesConfig().cookieNamePrefix+c+"."+a.getCookiesConfig().trackerSiteId+"."+a.getCookiesConfig().domainHash},getCookie:function(c){return a.getCookiesConfig().cookiesDisabled?
0:(c=(new RegExp("(^|;)[ ]*"+c+"=([^;]*)")).exec(a.documentAlias.cookie))?a.decodeWrapper(c[2])||0:0},setCookie:function(c,e,g){var h=a.getCookiesConfig();h.msToExpire=g?g.msToExpire||h.msToExpire:h.msToExpire;h.path=g?g.path||h.path:h.path;if(!h.cookiesDisabled){g=a.documentAlias;e=a.encodeWrapper(e);if(h.msToExpire){var n=new Date;n.setTime(n.getTime()+h.msToExpire)}c=c+"="+e+(h.msToExpire?";expires="+n.toGMTString():"")+";path="+(h.path||"/")+(h.domain?";domain="+h.domain:"")+(h.isSecure?";secure":
"")+";SameSite=Lax";g.cookie=c}},deleteCookie:function(c){this.setCookie(c,"",{msToExpire:-86400})},hasCookies:function(){if(a.getCookiesConfig().cookiesDisabled)return"0";if(!w(a.navigatorAlias.cookieEnabled)){var c=this.getCookieName("_pk_testcookie");this.setCookie(c,"1");var e="1"===this.getCookie(c)?"1":"0";this.deleteCookie(c);return e}return a.navigatorAlias.cookieEnabled?"1":"0"}}}function pc(a){var c=function(ya,Z){return ya<<Z|ya>>>32-Z},e=function(ya){var Z="",ba;for(ba=7;0<=ba;ba--){var wb=
ya>>>4*ba&15;Z+=wb.toString(16)}return Z},g,h=[],n=1732584193,m=4023233417,p=2562383102,u=271733878,v=3285377520,q=[];a=unescape(encodeURIComponent(a));var r=a.length;for(g=0;g<r-3;g+=4){var F=a.charCodeAt(g)<<24|a.charCodeAt(g+1)<<16|a.charCodeAt(g+2)<<8|a.charCodeAt(g+3);q.push(F)}switch(r&3){case 0:g=2147483648;break;case 1:g=a.charCodeAt(r-1)<<24|8388608;break;case 2:g=a.charCodeAt(r-2)<<24|a.charCodeAt(r-1)<<16|32768;break;case 3:g=a.charCodeAt(r-3)<<24|a.charCodeAt(r-2)<<16|a.charCodeAt(r-1)<<
8|128}for(q.push(g);14!==(q.length&15);)q.push(0);q.push(r>>>29);q.push(r<<3&4294967295);for(a=0;a<q.length;a+=16){for(g=0;16>g;g++)h[g]=q[a+g];for(g=16;79>=g;g++)h[g]=c(h[g-3]^h[g-8]^h[g-14]^h[g-16],1);F=n;r=m;var K=p;var J=u;var U=v;for(g=0;19>=g;g++){var H=c(F,5)+(r&K|~r&J)+U+h[g]+1518500249&4294967295;U=J;J=K;K=c(r,30);r=F;F=H}for(g=20;39>=g;g++)H=c(F,5)+(r^K^J)+U+h[g]+1859775393&4294967295,U=J,J=K,K=c(r,30),r=F,F=H;for(g=40;59>=g;g++)H=c(F,5)+(r&K|r&J|K&J)+U+h[g]+2400959708&4294967295,U=J,J=
K,K=c(r,30),r=F,F=H;for(g=60;79>=g;g++)H=c(F,5)+(r^K^J)+U+h[g]+3395469782&4294967295,U=J,J=K,K=c(r,30),r=F,F=H;n=n+F&4294967295;m=m+r&4294967295;p=p+K&4294967295;u=u+J&4294967295;v=v+U&4294967295}H=e(n)+e(m)+e(p)+e(u)+e(v);return H.toLowerCase()}function za(a,c){if("undefined"===typeof a)return!0;if("object"!==O(a)||null===a)return I("[".concat(c,"]: parameter 'options' have to be of type object or undefined. Received: ").concat(JSON.stringify(a))),!1;if("string"===typeof a.currencyCode||"undefined"===
typeof a.currencyCode)return!0;I("[".concat(c,"]: parameter 'options.currencyCode' has to be of type string or undefined Received: ").concat(JSON.stringify(a.currencyCode)));return!1}function V(a,c,e,g){if(a.addEventListener)return a.addEventListener(c,e,g),!0;if(a.attachEvent)return a.attachEvent("on"+c,e);a["on"+c]=e}function qd(a){var c={};if(!/MSIE/.test(navigator.userAgent)){if(navigator.mimeTypes&&navigator.mimeTypes.length)for(var e in xb)if(Object.prototype.hasOwnProperty.call(xb,e)){var g=
navigator.mimeTypes[xb[e]];c[e]=g&&g.enabledPlugin?"1":"0"}Ma(navigator.javaEnabled)&&navigator.javaEnabled()&&(c.java="1");Ma(window.GearsFactory)&&(c.gears="1");c.cookie=a()}a=parseInt(screen.width,10);e=parseInt(screen.height,10);c.res=a+"x"+e;return c}function qc(a,c){c||(c=pc);return c((navigator.userAgent||"")+(navigator.platform||"")+JSON.stringify(a)).slice(0,6)}function rc(a){var c=Math.floor((new Date).getTime()/1E3);a=qc(a);return String(c)+a}function rd(a,c,e,g){if(!e.crossDomainTrackingEnabled)return"";
g||(g=sb);a=g(a,e.configVisitorIdUrlParameter);if(!a)return"";a=String(a);g=/^[a-zA-Z0-9]+$/;if(16===a.length&&g.test(a))return a;if(32===a.length&&g.test(a)){a:{g=a.substr(16,32);e=e.configVisitorIdUrlParameterTimeoutInSeconds;g=String(g);c=qc(c);var h=c.length,n=g.substr(-1*h,h);if((g=parseInt(g.substr(0,g.length-h),10))&&n&&n===c){c=Math.floor((new Date).getTime()/1E3);if(0>=e){e=!0;break a}if(c>=g&&c<=g+e){e=!0;break a}}e=!1}if(e)return a.substr(0,16)}return""}function sc(a,c,e,g){if(a&&c.hasNodeAttribute(a,
"href")){var h=c.getAttributeValueFromNode(a,"href");h&&!Xa(h,g.configTrackerUrl)&&(h=(g.crossDomainTrackingLinkDecorator||tc)(h,e+rc(g.browserFeatures),g.configVisitorIdUrlParameter),null!==h&&c.setAnyAttribute(a,"href",h))}}function tc(a,c,e){a=fc(a,e);a=String(a);c||(c="");var g=document.createElement("a");g.href=a;a=g.search.split("&");a.push(encodeURIComponent(e)+"="+encodeURIComponent(c));""===a[0]&&a.shift();g.search=a.join("&");return g.href}function sd(a,c,e){for(var g=[],h=[],n=[],m=0;m<
a.length;m++){var p=a[m];p&&(-1<Y(c,p[0])?g.push(p):-1<Y(e,p[0])?n.push(p):h.push(p))}return{toApplyFirst:g,toApplySecond:h,toApplyLast:n}}function Za(a,c,e){w(e)||(e="");try{return a[c]||e}catch(g){return e}}function td(a){if(!a)return!0;var c,e=!0;for(c in a)Object.prototype.hasOwnProperty.call(a,c)&&(e=!1);return e}function Aa(){for(var a=0;a<arguments.length;a+=1){var c=arguments[a];if(!Array.isArray(c)){I("[".concat("_paq",".push()]: expected array as argument, got ",JSON.stringify(c),". Example: ",
"_paq",".push(['methodName', parameters]) or ","_paq",".push([function(){}])"));break}for(var e=c.shift(),g=0;g<S.length;g++){var h=S[g];if(Ma(e))e.apply(h,c);else if(R(e)){h[e]?h[e].apply(h,c):(h="The method '".concat(e,"' was not found in \"","_paq",'" variable.  Please have a look at the Piwik tracker documentation'),I(h));if("addTracker"===e)break;if("setTrackerUrl"===e||"setSiteId"===e)break}}}}function $a(a,c,e,g){if(a.removeEventListener)return a.removeEventListener(c,e,g),!0;if(a.detachEvent)return a.detachEvent("on"+
c,e);a["on"+c]===e&&delete a["on"+c]}function Ba(a){"complete"===B.readyState?a():A.addEventListener?A.addEventListener("load",a):A.attachEvent&&A.attachEvent("onload",a)}function Oa(a){var c=!1;(c=B.attachEvent?"complete"===B.readyState:"loading"!==B.readyState)?a():(B.addEventListener?V(B,"DOMContentLoaded",function g(){B.removeEventListener("DOMContentLoaded",g,!1);c||(c=!0,a())}):B.attachEvent&&(B.attachEvent("onreadystatechange",function g(){"complete"===B.readyState&&(B.detachEvent("onreadystatechange",
g),c||(c=!0,a()))}),B.documentElement.doScroll&&A===A.top&&function h(){if(!c){try{B.documentElement.doScroll("left")}catch(n){setTimeout(h,0);return}c=!0;a()}}()),V(A,"load",function(){c||(c=!0,a())},!1))}function ud(){var a="";try{a=A.top.document.referrer}catch(c){if(A.parent)try{a=A.parent.document.referrer}catch(e){a=""}}""===a&&(a=B.referrer);return a}function ca(a){return a&&String(a)===a?a.replace(/^\s+|\s+$/g,""):a}function uc(a,c){return a&&c?a.contains?a.contains(c):a===c?!0:a.compareDocumentPosition?
!!(a.compareDocumentPosition(c)&16):!1:!1}function yb(a){function c(g,h){if(A.getComputedStyle)return B.defaultView.getComputedStyle(g,null)[h];if(g.currentStyle)return g.currentStyle[h]}function e(g,h,n,m,p,u,v){var q=g.parentNode,r;a:{for(r=g.parentNode;r;){if(r===B){r=!0;break a}r=r.parentNode}r=!1}if(!r)return!1;if(9===q.nodeType)return!0;if("0"===c(g,"opacity")||"none"===c(g,"display")||"hidden"===c(g,"visibility"))return!1;w(h)&&w(n)&&w(m)&&w(p)&&w(u)&&w(v)||(h=g.offsetTop,p=g.offsetLeft,m=
h+g.offsetHeight,n=p+g.offsetWidth,u=g.offsetWidth,v=g.offsetHeight);if(a===g&&(0===v||0===u)&&"hidden"===c(g,"overflow"))return!1;if(q){if("hidden"===c(q,"overflow")||"scroll"===c(q,"overflow"))if(p+1>q.offsetWidth+q.scrollLeft||p+u-1<q.scrollLeft||h+1>q.offsetHeight+q.scrollTop||h+v-1<q.scrollTop)return!1;g.offsetParent===q&&(p+=q.offsetLeft,h+=q.offsetTop);return e(q,h,n,m,p,u,v)}return!0}return a?e(a):!1}function zb(a,c){function e(b){if(!1===Ab||!0===Bb){var d=new Date;null!==Cb&&18E5<d-Cb||
(d=H("ping=".concat(b),null,"ping"),b=b!==ra.PeriodicHeartbeat,p(d,L,null,b,b?"beacon":null))}}function g(b,d){var f=new Image(1,1);f.onload=function(){"function"===typeof d&&d()};b=-1!==b.indexOf("send_image=0")?b.replace("&send_image=0","&send_image=1"):b+"&send_image=1";f.src=aa+(0>aa.indexOf("?")?"?":"&")+b}function h(b,d,f){w(f)&&null!==f||(f=!0);try{var k=A.XMLHttpRequest?new A.XMLHttpRequest:A.ActiveXObject?new ActiveXObject("Microsoft.XMLHTTP"):null;k.open("POST",aa,!0);k.onreadystatechange=
function(){4!==this.readyState||200<=this.status&&300>this.status||!f?4===this.readyState&&"function"===typeof d&&d():g(b,d)};k.setRequestHeader("Content-Type",Db);k.send(b)}catch(l){f&&g(b,d)}}function n(b){b=(new Date).getTime()+b;if(!ab||b>ab)ab=b}function m(b,d){var f=(new Date).getTime();vc=f;Ca&&f<Ca?(f=Ca-f,setTimeout(b,f),d&&n(f+50),Ca+=50):(!1===Ca&&(Ca=f+800),b())}function p(b,d,f,k,l){if(Eb){var z=wc.getState();if("loading"===z.state){bb.push({type:"single",request:b,delay:d,callback:f,
force:k,method:l});return}"available"===z.state&&(b+=xc(z.hints))}Ma(Pa)&&(b=Pa(b));if(!cb&&b){var y=l||db,N=!f&&sa.sendBeacon&&A.Blob&&65536>=b.length,C=!0;l=function(){if("beacon"===y&&N){var fa=new A.Blob([String(b)],{type:Db});sa.sendBeacon(aa,fa)?C=!1:h(b,f)}else"POST"===y||2E3<String(b).length?h(b,f):g(b,f);C&&n(d)};k?l():m(l,C)}}function u(b,d){var f=cb?!1:b&&b.length;if(f){if(Eb){f=wc.getState();if("loading"===f.state){bb.push({type:"bulk",requests:b,delay:d});return}if("available"===f.state)for(var k=
0;k<b.length;k++)b[k]+=xc(f.hints)}if(Ma(Pa)){f=[];for(k=0;k<b.length;k++){var l=Pa(b[k]);l&&f.push(l)}if(0>=f.length)return;b=f}var z='{"requests":["?'+b.join('","?')+'"]}';m(function(){h(z,null,!1);"beacon"!==db&&n(d)},!1)}}function v(){yc=zc((eb||Qa)+(fb||"/")).slice(0,4)}function q(){var b=M.getCookieName("cvar");b=M.getCookie(b);return b.length&&(b=JSON.parse(b),wa(b))?b:{}}function r(){Da||(Da=rd(gb,ha,{crossDomainTrackingEnabled:Ea,configVisitorIdUrlParameter:"pk_vid",configVisitorIdUrlParameterTimeoutInSeconds:Ac},
Bc));var b=Math.round((new Date).getTime()/1E3),d=M.getCookieName("id");return(d=M.getCookie(d))?(d=d.split("."),d[0]=M.transformIfAMPCookie(d[0]),6>d.length&&(d[1]=b,d[2]=0,d[3]=b,d[4]="",d[5]=""),d.unshift("0"),Da.length&&(d[1]=Da),d):d=["1",Da.length?Da:"0"===M.hasCookies()?"":zc((sa.userAgent||"")+(sa.platform||"")+JSON.stringify(ha)+(new Date).getTime()+Math.random()).slice(0,16),b,0,b,"",""]}function F(){var b=r(),d=b[0],f=b[1],k=b[2],l=b[3],z=b[4],y=b[5];w(b[6])||(b[6]="");return{newVisitor:d,
uuid:f,createTs:k,visitCount:l,currentVisitTs:z,lastVisitTs:y,lastEcommerceOrderTs:b[6]}}function K(b){if(Fa){var d=Math.round((new Date).getTime()/1E3);w(b)||(b=F());b=b.uuid+"."+b.createTs+"."+b.visitCount+"."+d+"."+b.lastVisitTs+"."+b.lastEcommerceOrderTs;M.setCookie(M.getCookieName("id"),b,{msToExpire:Fb})}}function J(){var b=ta;ta=!1;var d;for(d=0;d<Gb.length;d++){var f=M.getCookieName(Gb[d]);0!==M.getCookie(f)&&M.deleteCookie(f)}ta=b}function U(b){if(b&&wa(b)){var d=[];for(f in b)Object.prototype.hasOwnProperty.call(b,
f)&&d.push(f);var f={};d.sort();var k=d.length,l;for(l=0;l<k;l++)f[d[l]]=b[d[l]];return f}}function H(b,d,f,k){function l(ia,vd){var Cc=JSON.stringify(ia);return 2<Cc.length?"&"+vd+"="+G(Cc):""}var z=new Date;var y=Math.round(z.getTime()/1E3);var N=T,C=M.getCookieName("ses"),fa=M.getCookieName("cvar"),ua=M.getCookie(C),Hb=Ra||gb;ta&&J();if(cb)return"";C=F();w(k)||(k="");var E=B.characterSet||B.charset;E&&"utf-8"!==E.toLowerCase()||(E=null);!ua&&(ua=Ga/1E3,!C.lastVisitTs||y-C.lastVisitTs>ua)&&(C.visitCount++,
C.lastVisitTs=C.currentVisitTs);ub(b,"action_name=")&&(Ab=hb,Bb=!!C.uuid,Cb=new Date);b+="&idsite="+Fa+"&rec=1&r="+String(Math.random()).slice(2,8)+"&h="+z.getHours()+"&m="+z.getMinutes()+"&s="+z.getSeconds()+"&url="+G(Ya(Hb,{discardHashTag:Sa,visitorIdUrlParameter:"pk_vid"}))+(Ib.length?"&urlref="+G(Ya(Ib,{discardHashTag:Sa,visitorIdUrlParameter:"pk_vid"})):"")+(Ha&&Ha.length?"&uid="+G(Ha):"")+(hb?"&uia=1":"")+(C.uuid?"&_id="+C.uuid:"")+"&_idts="+C.createTs+"&_idvc="+C.visitCount+(C.lastVisitTs?
"&_viewts="+C.lastVisitTs:"")+(String(C.lastEcommerceOrderTs).length?"&_ects="+C.lastEcommerceOrderTs:"")+(E?"&cs="+G(E):"")+"&ts_n="+G(ib||Jb)+"&ts_v="+G(Kb||Lb)+(Dc?"":"&rmip=1")+(Ec&&hb?"&dda=1":"");if(!Fc)for(x in ha)Object.prototype.hasOwnProperty.call(ha,x)&&(b+="&"+x+"="+ha[x]);z=[];if(d)for(x in d)Object.prototype.hasOwnProperty.call(d,x)&&/^dimension\d+$/.test(x)&&(y=x.replace("dimension",""),z.push(parseInt(y,10)),z.push(String(y)),b+="&"+x+"="+d[x],delete d[x]);d&&td(d)&&(d=null);for(x in da)Object.prototype.hasOwnProperty.call(da,
x)&&(y=-1===Y(z,x))&&(y=RegExp("[^\x00-\u007f]"),b=(-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/"))&&null!==da[x].match(y)?b+("&dimension"+x+"="+encodeURIComponent(da[x])):b+("&dimension"+x+"="+da[x]));for(x in ma)Object.prototype.hasOwnProperty.call(ma,x)&&(y=-1===Y(z,x))&&(b+="&dimension"+encodeURIComponent(x)+"="+encodeURIComponent(ma[x]));d?b+="&data="+G(JSON.stringify(d)):na&&(b+="&data="+G(JSON.stringify(na)));d=U(oa);z=U(jb);b+=l(d,"cvar");b+=l(z,"e_cvar");
if(T){b+=l(T,"_cvar");for(x in N)Object.prototype.hasOwnProperty.call(N,x)&&(""===T[x][0]||""===T[x][1])&&delete T[x];Gc&&M.setCookie(fa,JSON.stringify(T),{msToExpire:Ga})}var x=kd();N=null;Mb&&(Nb?N=Nb:x&&x.requestStart&&x.responseEnd&&(N=x.responseEnd-x.requestStart),null!==N&&(b+="&gt_ms="+Math.max(N,0)));N=x&&x.loadEventEnd&&0!==x.loadEventEnd&&x.fetchStart&&0!==x.fetchStart;Mb&&("log"===f||"ping"===f)&&2>=kb&&!Hc&&N&&(b+=ld(x),Hc=!0);lb&&(b+="&pv_id="+lb);C.lastEcommerceOrderTs=w(k)&&String(k).length?
k:C.lastEcommerceOrderTs;K(C);M.setCookie(M.getCookieName("ses"),"*",{msToExpire:Ga});Ob.length&&(b+="&"+Ob);return b}function ya(b){if(!wa(b))return I("Invalid ecommerce product: "+JSON.stringify(b)),!1;if(!Object.prototype.hasOwnProperty.call(b,"sku"))return I("Missing required SKU property in ecommerce product: "+JSON.stringify(b)+"."),!1;var d=O(b.sku);return"string"!==d&&"number"!==d?(I("Product.sku has to be of type string or number. Received: ".concat(d,". In product: ").concat(JSON.stringify(b))),
!1):Object.prototype.hasOwnProperty.call(b,"customDimensions")&&!wa(b.customDimensions)?(I('Invalid "customDimensions" property. Expected Object type, but got: '+JSON.stringify(b)+"."),!1):!0}function Z(b,d,f,k){var l=new Date,z=[];var y=""+ja("");y+="&e_t="+b;null!==k&&void 0!==k&&k.currencyCode&&(y+="&cur="+k.currencyCode);if(f){b=f.orderId;k=f.grandTotal;var N=f.subTotal;var C=f.tax;var fa=f.shipping;f=f.discount;if(b){y+="&ec_id="+G(b);var ua=Math.round(l.getTime()/1E3)}y+="&revenue="+k;qa(N)&&
(y+="&ec_st="+N);qa(C)&&(y+="&ec_tx="+C);qa(fa)&&(y+="&ec_sh="+fa);qa(f)&&(y+="&ec_dt="+f)}if(d){for(l=0;l<d.length;l+=1){w(d[l].name)||(d[l].name="");if(!w(d[l].category))d[l].category="";else if(d[l].category instanceof Array)for(f=0;f<d[l].category.length;f+=1)R(d[l].category[f])||(d[l].category[f]="");w(d[l].price)&&0!==String(d[l].price).length||(d[l].price=0);w(d[l].quantity)&&0!==String(d[l].quantity).length||(d[l].quantity=1);w(d[l].brand)&&0!==String(d[l].brand).length||(d[l].brand="");w(d[l].variant)&&
0!==String(d[l].variant).length||(d[l].variant="");w(d[l].customDimensions)||(d[l].customDimensions={});f=z;b=f.push;a:for(k=[String(d[l].sku),String(d[l].name),d[l].category,d[l].price,d[l].quantity,d[l].brand,String(d[l].variant),d[l].customDimensions].slice();0<k.length;){N=k[k.length-1];if(!(C=""===N)&&(C=wa(N)))b:{C=void 0;for(C in N)if(Object.hasOwnProperty.call(N,C)){C=!1;break b}C=!0}if(C)k.pop();else break a}b.call(f,k)}y+="&ec_products="+G(JSON.stringify(z))}y=H(y,na,"ecommerce",ua);p(y,
L)}function ba(b){var d,f=!0;if(b instanceof Array){for(d=0;d<b.length;d+=1)f=f&&ya(b[d]);return f}I("Invalid ecommerce products. Expected value: array of objects. Recieved: "+JSON.stringify(b)+".")}function wb(b,d){var f;if("object"!==O(b)||null===b)return I("Invalid paymentInformation. Expected object. Recieved: "+JSON.stringify(b)+"."),!1;for(f=0;f<d.length;f+=1){var k=d[f];var l=b[k];if("orderId"===k){if(!w(l)||""===String(l))return I('Invalid paymentInformation. Expected object containing "'+
k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}else if(!qa(l))return I('Invalid paymentInformation. Expected object containing [number] "'+k+'" attribute. Recieved: '+JSON.stringify(b)+"."),!1}return!0}function Ic(b,d,f){za(f,"ecommerceCartUpdate")||(f=void 0);qa(d)?ba(b)&&Z("cart-update",b,{grandTotal:d},f):I('ecommerceCartUpdate requires [number] "grandTotal" parameter. Recieved: '+JSON.stringify(d)+".")}function Jc(b,d,f){za(f,"ecommerceOrder")||(f=void 0);ba(b)&&wb(d,["orderId","grandTotal"])&&
Z("order",b,d,f)}function Kc(){var b,d=[];if(X){for(b in X)if(Object.prototype.hasOwnProperty.call(X,b)){var f={sku:X[b][0],name:X[b][1],category:X[b][2],price:X[b][3],quantity:X[b][4]};d.push(f)}return d}return[]}function ja(b){b=(b=b||mb)&&b.text?b.text:b;if(!R(b)){var d=document.getElementsByTagName("title");d&&w(d[0])&&(b=d[0].text)}return"action_name="+G(b)}function nb(b,d,f,k){if(b=D.buildInteractionRequestParams(b,d,f,k))return H("".concat(b,"&").concat(ja()),null,"contentInteraction")}function Pb(b,
d){if(!b||!d)return!1;var f,k=D.findTargetNodes(b);for(f=0;f<k.length;f++){var l=k[f];if(uc(l,d)&&D.shouldIgnoreInteraction(l))return!1}k=D.findTargetNodesNoDefault(b);if(!k||0===k.length)return!0;for(f=0;f<k.length;f++)if(l=k[f],uc(l,d))return!0;return!1}function Lc(b,d,f){if(b){var k=D.findParentContentNode(b);if(k&&Pb(k,b)&&(b=D.buildContentBlock(k)))return!b.target&&f&&(b.target=f),D.buildInteractionRequestParams(d,b.name,b.piece,b.target)}}function Mc(b){if(!pa||!pa.length)return!1;var d,f;for(d=
0;d<pa.length;d++)if((f=pa[d])&&f.name===b.name&&f.piece===b.piece&&f.target===b.target)return!0;return!1}function Nc(b){return function(d){if(b){var f=D.findParentContentNode(b),k;d&&(k=d.target||d.srcElement);k||(k=b);if(Pb(f,k)){"beacon"!==db&&n(L);t.isLinkElement(b)&&t.hasNodeAttributeWithValue(b,"href")&&t.hasNodeAttributeWithValue(b,D.CONTENT_TARGET_ATTR)&&(d=t.getAttributeValueFromNode(b,"href"),!Xa(d,aa)&&b.wasContentTargetAttrReplaced&&t.setAnyAttribute(b,D.CONTENT_TARGET_ATTR,""));d=mc(b,
D,{configTrackerUrl:aa,configDownloadClasses:Qb,configLinkClasses:Rb,configDownloadExtensions:ka,configHostsAlias:la});if(Ia&&d&&d.type)return d.type;if(k=D.buildContentBlock(f))if(f=k.name,d=k.piece,k=t.getAttributeValueFromNode(b,D.CONTENT_TARGET_ATTR)||k.target,f=nb("click",f,d,k))return p("".concat(f,"&").concat(ja()),L),f}}}}function Oc(b){if(b&&b.length){var d,f,k;for(d=0;d<b.length;d++){var l=D.findTargetNodes(b[d]);for(k=0;k<l.length;k++)(f=l[k])&&!f.contentInteractionTrackingSetupDone&&(f.contentInteractionTrackingSetupDone=
!0,V(f,"click",Nc(f)))}}}function Pc(b,d){if(!b||!b.length)return[];var f,k;for(f=0;f<b.length;f++)Mc(b[f])?(b.splice(f,1),f--):pa.push(b[f]);if(!b||!b.length)return[];Oc(d);var l=[];for(f=0;f<b.length;f++)(k=H("".concat(D.buildImpressionRequestParams(b[f].name,b[f].piece,b[f].target),"&").concat(ja()),void 0,"contentImpressions"))&&l.push(k);return l}function Ta(b){var d=D.collectContent(b);return Pc(d,b)}function Sb(b){if(!b||!b.length)return[];var d;for(d=0;d<b.length;d++)D.isNodeVisible(b[d])||
(b.splice(d,1),d--);return b&&b.length?Ta(b):[]}function Qc(b,d,f){b=D.buildImpressionRequestParams(b,d,f);return H("".concat(b,"&").concat(ja()),null,"contentImpression")}function Rc(b,d){if(b){var f=D.findParentContentNode(b);if(f=D.buildContentBlock(f))return d||(d="Unknown"),nb(d,f.name,f.piece,f.target)}}function Sc(b,d,f,k,l,z){if(0===ca(String(b)).length||0===ca(String(d)).length)return I("Error while logging event: Parameters `category` and `action` must not be empty or filled with whitespaces"),
!1;var y=H;b="e_c="+G(b)+"&e_a="+G(d)+(w(f)?"&e_n="+G(f):"")+(w(k)?"&e_v="+G(k):"");l=y(b+"&"+ja(""),l,"event");p(l,L,z)}function Tc(b,d,f,k,l){d="".concat(ja(),"&").concat(d,"=").concat(G(Ya(b,{discardHashTag:Sa,visitorIdUrlParameter:"pk_vid"})));(b=Lc(l,"click",b))&&(d+="&"+b);f=H(d,f,"link");p(f,L,k,!0,"beacon")}function W(b){var d,f,k=["","webkit","ms","moz"];if(!Uc)for(f=0;f<k.length;f++){var l=k[f];if(Object.prototype.hasOwnProperty.call(B,ic(l,"hidden"))){"prerender"===B[ic(l,"visibilityState")]&&
(d=!0);break}}d?V(B,l+"visibilitychange",function y(){B.removeEventListener(l+"visibilitychange",y,!1);b()}):b()}function Tb(b){if(Ea){var d=tb(b);if(id(d,la)){sc(d,t,F().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:aa,browserFeatures:ha,crossDomainTrackingLinkDecorator:Ub});return}}if((d=mc(b,D,{configTrackerUrl:aa,configDownloadClasses:Qb,configLinkClasses:Rb,configDownloadExtensions:ka,configHostsAlias:la}))&&d.type)Tc(d.href,d.type,void 0,null,b);else if(Ea){b=tb(b);d=D;var f=la,
k=Qa,l=t.getAttributeValueFromNode(b,"href");if(l)if(l=String(l),0!==l.indexOf("//")&&0!==l.indexOf("http://")&&0!==l.indexOf("https://"))d=!1;else{var z=ec(l),y=z.pathname||Wa(l,d);l=(z.hostname||La(l)).toLowerCase();d=lc(l,y,f,d)&&!rb(k,Na(l))?!0:!1}else d=!1;d&&sc(b,t,F().uuid,{configVisitorIdUrlParameter:"pk_vid",configTrackerUrl:aa,browserFeatures:ha,crossDomainTrackingLinkDecorator:Ub})}}function Ua(b){return function(d){d=d||A.event;a:{var f=d;var k=f.which,l=O(f.button);k||"undefined"===l||
(B.all&&!B.addEventListener?f.button&1?k=1:f.button&2?k=3:f.button&4&&(k=2):0===f.button||"0"===f.button?k=1:f.button&1?k=2:f.button&2&&(k=3));switch(k){case 1:f="left";break a;case 2:f="middle";break a;case 3:f="right";break a}f=void 0}k=d.target||d.srcElement;"click"===d.type?(d=!1,b&&"middle"===f&&(d=!0),k&&!d&&Tb(k)):"mousedown"===d.type?"middle"===f&&k?(ob=f,pb=k):ob=pb=null:"mouseup"===d.type?(f===ob&&k===pb&&Tb(k),ob=pb=null):"contextmenu"===d.type&&Tb(k)}}function wd(b){function d(k){var l=
k.target;if(l.closest)l=l.closest("a");else for(;l&&"A"!==l.tagName;)l=l.parentNode;Vb&&l&&!vb(Vc,"ignore").test(l.className)&&Ua(b)(k)}function f(){$a(document.body,"click",d,!1);b&&($a(document.body,"mouseup",d,!1),$a(document.body,"mousedown",d,!1),$a(document.body,"contextmenu",d,!1))}Ia||(V(document.body,"click",d,!1),b&&(V(document.body,"mouseup",d,!1),V(document.body,"mousedown",d,!1),V(document.body,"contextmenu",d,!1)),Ia=f)}function Wc(b,d,f){function k(){l=!0}if(Ja)return!0;Ja=!0;var l=
!1,z,y;Ba(function(){function N(E){setTimeout(function(){Ja&&(l=!1,f.trackVisibleContentImpressions(),N(E))},E)}function C(E){setTimeout(function(){Ja&&(l&&(l=!1,f.trackVisibleContentImpressions()),C(E))},E)}function fa(E){if(!E)return!1;var x=E.getBoundingClientRect();if(0>=x.width||0>=x.height)return!1;x=null;A.getComputedStyle?x=B.defaultView.getComputedStyle(E,null):!x&&E.currentStyle?x=E.currentStyle:x||(x={});return"0"===x.opacity||"none"===x.display||"hidden"===x.visibility?!1:E.parentNode instanceof
Element?fa(E.parentNode):!0}function ua(E){var x=[],ia;for(ia=0;ia<E.length;ia+=1)E[ia].isIntersecting&&fa(E[ia].target)&&D.isOrWasNodeInViewport(E[ia].target)&&x.push(E[ia].target);E=Ta(x);u(E,L)}function Hb(){if(A.IntersectionObserver){va||(va=new A.IntersectionObserver(ua,{threshold:0}));var E=D.findContentNodes();for(y=0;y<E.length;y+=1)E[y].getAttribute(D.CONTENT_WATCHED_ATTR)||(va.observe(E[y]),E[y].setAttribute(D.CONTENT_WATCHED_ATTR,"1"));return!0}return!1}(b||d&&0<d)&&Hb();if(b){z=["scroll",
"resize"];for(y=0;y<z.length;y++)B.addEventListener?B.addEventListener(z[y],k):A.attachEvent("on"+z[y],k);C(100)}d&&0<d&&(d=parseInt(d,10),N(d))})}function Xc(b,d,f,k){if(Wb){var l=String(b).substring(0,16E3);W(function(){var z=d+":"+f;k&&(z+=":"+k);var y=JSON.stringify({category:"JavaScript Errors",action:z,message:l});Yc&&-1!==Y(Xb,y)||(Xb.push(y),Sc("JavaScript Errors",z,l))})}}var Yb=hd(B.domain,A.location.href,ud()),Qa=Na(Yb[0]),gb=Yb[1],Ib=Yb[2],Wb=!1,db="beacon",Dc=!0,Ec=!1,Eb=!1,Db="application/x-www-form-urlencoded; charset=UTF-8",
aa=a||"",Zb="",Ob="",Fa=c||"",hb=!1,Fc=!1,Ab=null,Bb=null,Ha="",Da="",$b=10,Ra,mb="",ka="7z aac apk arc arj asf asx avi azw3 bin csv deb dmg doc docx epub exe flv gif gz gzip hqx ibooks jar jpg jpeg js mobi mp2 mp3 mp4 mpg mpeg mov movie msi msp odb odf odg ods odt ogg ogv pdf phps png ppt pptx qt qtm ra ram rar rpm sea sit tar tbz tbz2 bz bz2 tgz torrent txt wav wma wmv wpd xls xlsx xml z zip".split(" "),la=[Qa],Vc=[],Qb=[],Rb=[],L=500,Cb=null,Zc=!1,Sa,na,$c="_pk_",Ac=180,eb,fb,ad=!1,ta=!1,bd=!0,
cb,Uc,Fb=339552E5,Ga=18E5,Mb=!0,Nb=0,Gc=!1,T=!1,Pa,oa={},jb={},da={},ma={},ac=200,X={},ha={},pa=[],Ja=!1,va,Ca=!1,Ia=!1,Vb=!1,Ea=!1,Ub=tc,Bc=sb,vc=null,ob,pb,zc=pc,yc,lb,kb=0,Yc=!1,Xb=[],Gb=["id","ses","cvar"],Jb="jstc",Lb="2.28.1",ib="",Kb="",wc=md({onResolve:function(){for(var b=0;b<bb.length;b++){var d=bb[b];if("single"===d.type)p(d.request,d.delay,d.callback,d.force,d.method);else if("bulk"===d.type)u(d.requests,d.delay);else throw Error("[processQueue] unprocessable request type: ".concat(d));
}}});try{mb=B.title}catch(b){mb=""}var Ka=nd({onPing:e}),M=pd({decodeWrapper:xd,encodeWrapper:G,getCookiesConfig:function(){return{cookiesDisabled:ta,domain:eb,path:fb,isSecure:ad,trackerSiteId:Fa,cookieNamePrefix:$c,domainHash:yc}},documentAlias:B,navigatorAlias:sa}),bb=[];this.setCustomVariableMaximumLength=function(b){ac=b};ha=qd(M.hasCookies);v();this.getQuery=function(){return t};this.getContent=function(){return D};this.buildContentImpressionRequest=Qc;this.buildContentInteractionRequest=nb;
this.buildContentInteractionRequestNode=Rc;this.getContentImpressionsRequestsFromNodes=Ta;this.getCurrentlyVisibleContentImpressionsRequestsIfNotTrackedYet=Sb;this.trackCallbackOnLoad=Ba;this.trackCallbackOnReady=Oa;this.buildContentImpressionsRequests=Pc;this.wasContentImpressionAlreadyTracked=Mc;this.appendContentInteractionToRequestIfPossible=Lc;this.setupInteractionsTracking=Oc;this.trackContentImpressionClickInteraction=Nc;this.internalIsNodeVisible=yb;this.isNodeAuthorizedToTriggerInteraction=
Pb;this.getDomains=function(){return la};this.getConfigIdPageView=function(){return lb};this.getConfigDownloadExtensions=function(){return ka};this.enableTrackOnlyVisibleContent=function(b,d){return Wc(b,d,this)};this.clearTrackedContentImpressions=function(){pa=[]};this.getTrackedContentImpressions=function(){return pa};this.clearEnableTrackOnlyVisibleContent=function(){Ja=!1;va&&va.disconnect();va=null};this.disableLinkTracking=function(){"function"===typeof Ia&&Ia();Vb=Ia=!1};this.getConfigVisitorCookieTimeout=
function(){return Fb};this.removeAllAsyncTrackersButFirst=function(){S=[S[0]]};this.ping=function(){var b=H("ping=6",null,"ping");p(b,L)};this.getVisitorId=function(){return F().uuid};this.getVisitorInfo=function(){return r()};this.setTrackerUrl=function(b){aa=b};this.getTrackerUrl=function(){return aa};this.getPiwikUrl=function(){var b=this.getTrackerUrl();if(Zb)b=Zb;else{b=D.toAbsoluteUrl(b);var d=String(b);-1!==d.indexOf("?")&&(d=b.indexOf("?"),b=b.slice(0,d));xa(b,"ppms.php")?b=jc(b,8):xa(b,".php")&&
(d=b.lastIndexOf("/"),b=b.slice(0,d+1));xa(b,"/js/")&&(b=jc(b,3))}return b};this.addTracker=function(b,d){if(!d)throw Error("A siteId must be given to add a new tracker");w(b)&&null!==b||(b=this.getTrackerUrl());var f=new zb(b,d);S.push(f);return f};this.getSiteId=function(){return Fa};this.setSiteId=function(b){Fa=b;K();if(bd){var d=this.getTrackerUrl(),f=B.createElement("script");f.setAttribute("id","ppas_container_configuration");f.setAttribute("data-appid",b);b=f.setAttribute;var k=B.createElement("a");
k.href=d;b.call(f,"data-host",k.host);B.getElementsByTagName("head")[0].appendChild(f)}};this.setVisitorIdCookie=function(){K()};this.resetUserId=function(){Ha=""};this.setUserIsAnonymous=function(b){hb=b};this.setSessionIdStrictPrivacyMode=function(b){Fc=b};this.setTimingDataSamplingOnPageLoad=function(b){!0===b&&(b=1);!1===b&&(b=0);b=parseInt(b,10);0>b?b=0:100<b&&(b=100);$b=b};this.getTimingDataSamplingOnPageLoad=function(){return $b};this.setUserId=function(b){w(b)&&b.length&&(Ha=b)};this.getUserId=
function(){return Ha};this.setCustomData=function(b,d){wa(b)?na=b:(na||(na={}),na[b]=d)};this.getCustomData=function(){return na};this.setCustomRequestProcessing=function(b){Pa=b};this.appendToTrackingUrl=function(b){Ob=b};this.getRequest=function(b){return H(b)};this.setCustomDimension=function(b,d){b=parseInt(b,10);0<b&&(Object.prototype.hasOwnProperty.call(ma,b)?console.warn("Custom dimension "+b+' was already set by "setCustomDimensionValue" method. Value set by "setCustomDimension" will be ignored.'):
(w(d)||(d=""),R(d)||(d=String(d)),da[b]=d))};this.getCustomDimension=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(da,b))return da[b]};this.deleteCustomDimension=function(b){b=parseInt(b,10);0<b&&(delete da[b],delete ma[b])};this.setCustomDimensionValue=function(b,d){b=parseInt(b,10);0<b&&(w(d)||(d=""),R(d)||(d=String(d)),ma[b]=d,delete da[b])};this.getCustomDimensionValue=function(b){b=parseInt(b,10);if(0<b&&Object.prototype.hasOwnProperty.call(ma,b))return ma[b]};this.setCustomVariable=
function(b,d,f,k){w(k)||(k="visit");w(d)&&(w(f)||(f=""),0<b&&(d=R(d)?d:String(d),f=R(f)?f:String(f),d=[d.slice(0,ac),f.slice(0,ac)],"visit"===k||2===k?(!1===T&&(T=q()),T[b]=d):"page"===k||3===k?oa[b]=d:"event"===k&&(jb[b]=d)))};this.getCustomVariable=function(b,d){w(d)||(d="visit");if("page"===d||3===d)var f=oa[b];else if("event"===d)f=jb[b];else if("visit"===d||2===d)!1===T&&(T=q()),f=T[b];return!w(f)||f&&""===f[0]?!1:f};this.deleteCustomVariable=function(b,d){this.getCustomVariable(b,d)&&this.setCustomVariable(b,
"","",d)};this.deleteCustomVariables=function(b){if("page"===b||3===b)oa={};else if("event"===b)jb={};else if("visit"===b||2===b)T={}};this.storeCustomVariablesInCookie=function(){Gc=!0};this.setLinkTrackingTimer=function(b){L=b};this.getLinkTrackingTimer=function(){return L};this.setDownloadExtensions=function(b){R(b)&&(b=b.split("|"));ka=b};this.addDownloadExtensions=function(b){var d;R(b)&&(b=b.split("|"));for(d=0;d<b.length;d++)ka.push(b[d])};this.removeDownloadExtensions=function(b){var d,f=
[];R(b)&&(b=b.split("|"));for(d=0;d<ka.length;d++)-1===Y(b,ka[d])&&f.push(ka[d]);ka=f};this.setDomains=function(b){la=R(b)?[b]:b;b=!1;for(var d=0;d<la.length;d++){var f=String(la[d]);if(rb(Qa,Na(f))){b=!0;break}if((f=Wa(f,D))&&"/"!==f&&"/*"!==f){b=!0;break}}b||la.push(Qa)};this.enableCrossDomainLinking=function(){Ea=!0};this.disableCrossDomainLinking=function(){Ea=!1};this.isCrossDomainLinkingEnabled=function(){return Ea};this.customCrossDomainLinkDecorator=function(b){Ub=b};this.customCrossDomainLinkVisitorIdGetter=
function(b){Bc=b};this.setCrossDomainLinkingTimeout=function(b){Ac=b};this.getCrossDomainLinkingUrlParameter=function(){var b=F().uuid;return G("pk_vid")+"="+G(b+rc(ha))};this.setIgnoreClasses=function(b){Vc=R(b)?[b]:b};this.setRequestMethod=function(b){db=b||"beacon"};this.setRequestContentType=function(b){Db=b||"application/x-www-form-urlencoded; charset=UTF-8"};this.setReferrerUrl=function(b){Ib=b};this.setCustomUrl=function(b){var d=gb,f=Sa;gc(b)?Ra=b:"/"===b.slice(0,1)?Ra=gc(d)+"://"+La(d)+b:
(d=Ya(d,{discardHashTag:f,visitorIdUrlParameter:"pk_vid"}),f=d.indexOf("?"),0<=f&&(d=d.slice(0,f)),f=d.lastIndexOf("/"),f!==d.length-1&&(d=d.slice(0,f+1)),Ra=d+b)};this.getCurrentUrl=function(){return Ra||gb};this.setDocumentTitle=function(b){mb=b};this.setAPIUrl=function(b){Zb=b};this.setDownloadClasses=function(b){Qb=R(b)?[b]:b};this.setLinkClasses=function(b){Rb=R(b)?[b]:b};this.discardHashTag=function(b){Sa=b};this.setCookieNamePrefix=function(b){$c=b;T=q()};this.setCookieDomain=function(b){eb=
Na(b);v()};this.getCookieDomain=function(){return eb};this.hasCookies=function(){return"1"===M.hasCookies()};this.setSessionCookie=function(b,d,f){if(!b)throw Error("Missing cookie name");w(f)||(f=Ga);Gb.push(b);M.setCookie(M.getCookieName(b),d,{msToExpire:f})};this.getCookie=function(b){b=M.getCookie(M.getCookieName(b));return 0===b?null:b};this.setCookiePath=function(b){fb=b;v()};this.getCookiePath=function(){return fb};this.setVisitorCookieTimeout=function(b){Fb=1E3*b};this.setSessionCookieTimeout=
function(b){Ga=1E3*b};this.getSessionCookieTimeout=function(){return Ga};this.setReferralCookieTimeout=function(){};this.setSecureCookie=function(b){ad=b};this.disableCookies=function(){ta=!0;Fa&&J()};this.enableCookies=function(){ta=!1};this.deleteCookies=function(){J()};this.setSiteInspectorSetup=function(b){bd=b};this.setDoNotTrack=function(b){var d=sa.doNotTrack||sa.msDoNotTrack;(cb=b&&("yes"===d||"1"===d))&&this.disableCookies()};this.addListener=function(b,d){var f=d;"undefined"===O(f)&&(f=
!0);V(b,"click",Ua(f),!1);f&&(V(b,"mouseup",Ua(f),!1),V(b,"mousedown",Ua(f),!1),V(b,"contextmenu",Ua(f),!1))};this.enableLinkTracking=function(b){this.disableLinkTracking();"undefined"===typeof b&&(b=!0);Vb=!0;W(function(){Oa(function(){wd(b)})})};this.enableJSErrorTracking=function(b){w(b)||(b=!0);if(!Wb){Wb=!0;Yc=b;var d=A.onerror;A.onerror=function(f,k,l,z,y){Xc(f,k,l,z);return d?d(f,k,l,z,y):!1}}};this.disablePerformanceTracking=function(){Mb=!1};this.setGenerationTimeMs=function(b){Nb=parseInt(b,
10)};this.enableHeartBeatTimer=function(b){if(b){var d=nc(b);if(!d.isValid){I(d.error);return}}else b=oc;Ka.setTimings(b);Zc=!0;null!==vc&&Ka.enable()};this.disableHeartBeatTimer=function(){Ka.disable()};this.killFrame=function(){A.location!==A.top.location&&(A.top.location=A.location)};this.redirectFile=function(b){"file:"===A.location.protocol&&(A.location=b)};this.setCountPreRendered=function(b){Uc=b};this.trackGoal=function(b,d,f,k){za(k,"trackGoal")||(k=void 0);W(function(){var l=k;l=H("idgoal="+
b+(d?"&revenue="+d:"")+"&"+ja("")+(null!==l&&void 0!==l&&l.currencyCode?"&cur="+l.currencyCode:""),f,"goal");p(l,L)})};this.trackLink=function(b,d,f,k){W(function(){Tc(b,d,f,k)})};this.getNumTrackedPageViews=function(){return kb};this.trackHeartBeat=function(b){var d=!B.hasFocus||B.hasFocus();Ka.isEnabled()&&d&&(!1===Ab||!0===Bb)&&(d=ra.PeriodicHeartbeat,b.lastHeartbeat&&(d=ra.LastHeartbeat),b.blurHeartbeat&&(d=ra.BlurHeartbeat),e(d))};this.trackPageView=function(b,d,f){pa=[];Xb=[];W(function(){kb++;
var k="",l;for(l=0;6>l;l++)k+="abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(Math.floor(62*Math.random()));lb=k;k=H(ja(b),d,"log");p(k,L,f);Zc&&!Ka.isEnabled()&&Ka.enable()});1>=kb&&$b>=Math.floor(100*Math.random()+1)&&Ba(function(){setTimeout(function(){var k=H("ping=5",null,"ping");p(k,L)},0)})};this.trackAllContentImpressions=function(){W(function(){Oa(function(){var b=D.findContentNodes();b=Ta(b);u(b,L)})})};this.trackVisibleContentImpressions=function(b,d){w(b)||(b=!0);
w(d)||(d=750);Wc(b,d,this);va||W(function(){Ba(function(){var f=D.findContentNodes();f=Sb(f);u(f,L)})})};this.trackContentImpression=function(b,d,f){b=ca(b);d=ca(d);f=ca(f);b&&(d=d||"Unknown",W(function(){var k=Qc(b,d,f);p(k,L)}))};this.trackContentImpressionsWithinNode=function(b){b&&W(function(){Ja?Ba(function(){var d=D.findContentNodesWithinNode(b);d=Sb(d);u(d,L)}):Oa(function(){var d=D.findContentNodesWithinNode(b);d=Ta(d);u(d,L)})})};this.trackContentInteraction=function(b,d,f,k){b=ca(b);d=ca(d);
f=ca(f);k=ca(k);b&&d&&(f=f||"Unknown",W(function(){var l=nb(b,d,f,k);p(l,L)}))};this.trackContentInteractionNode=function(b,d){b&&W(function(){var f=Rc(b,d);p(f,L)})};this.logAllContentBlocksOnPage=function(){var b=D.findContentNodes();b=D.collectContent(b);console.log(b)};this.trackEvent=function(b,d,f,k,l,z){w(k)&&!qa(k)&&I("[trackEvent]: Value parameter must be a number or number representation. Received: ".concat(JSON.stringify(k)));W(function(){Sc(b,d,f,k,l,z)})};this.trackSiteSearch=function(b,
d,f,k){W(function(){var l=H("search="+G(b)+(d?"&search_cats="+G(JSON.stringify(R(d)?[d]:d)):"")+(w(f)?"&search_count="+f:""),k,"sitesearch");p(l,L)})};this.setEcommerceView=function(b,d,f,k){w(f)&&f.length?f instanceof Array&&(f=JSON.stringify(f)):f="";oa[5]=["_pkc",f];w(k)&&String(k).length&&(oa[2]=["_pkp",k]);if(w(b)&&b.length||w(d)&&d.length)w(b)&&b.length&&(oa[3]=["_pks",b]),w(d)&&d.length||(d=""),oa[4]=["_pkn",d]};this.getEcommerceItems=function(){return JSON.parse(JSON.stringify(X))};this.addEcommerceItem=
function(b,d,f,k,l){b.length&&(X[b]=[b,d,f,k,l])};this.removeEcommerceItem=function(b){b.length&&delete X[b]};this.clearEcommerceCart=function(){X={}};this.trackEcommerceOrder=function(b,d,f,k,l,z){String(b).length&&w(d)&&(Jc(Kc(),{orderId:b,grandTotal:d,subTotal:f,tax:k,shipping:l,discount:z}),X={})};this.trackEcommerceCartUpdate=function(b){Ic(Kc(),b)};this.ecommerceProductDetailView=function(b,d){za(d,"ecommerceProductDetailView")||(d=void 0);ba(b)&&Z("product-detail-view",b,void 0,d)};this.ecommerceAddToCart=
function(b,d){za(d,"ecommerceAddToCart")||(d=void 0);ba(b)&&Z("add-to-cart",b,void 0,d)};this.ecommerceRemoveFromCart=function(b,d){za(d,"ecommerceRemoveFromCart")||(d=void 0);ba(b)&&Z("remove-from-cart",b,void 0,d)};this.ecommerceCartUpdate=Ic;this.ecommerceOrder=Jc;this.trackError=function(b){if(b){try{var d=yd.parse(b);var f=d[0]}catch(k){}Xc(Za(b,"message"),Za(f,"fileName"),Za(f,"lineNumber"),Za(f,"columnNumber"))}};this.trackRequest=function(b,d,f,k){W(function(){var l=H(b,d,k);p(l,L,f)})};this.deanonymizeUser=
function(){this.setUserIsAnonymous(0);var b=H("ping=4",null,"ping");p(b,L)};this.getTrackingSource=function(){return[Jb,Lb]};this.setTrackingSource=function(b,d){Jb=String(b);void 0!==d&&(Lb=String(d))};this.setTrackingSourceProvider=function(b,d){"string"!==typeof b?I("[setTrackingSourceProvider]: 'provider' has to be of type string"):"string"!==typeof d?I("[setTrackingSourceProvider]: 'providerVersion' has to be of type string"):(ib=b,Kb=d)};this.getTrackingSourceProvider=function(){if(ib)return[ib,
Kb]};this.setIpTracking=function(b){Dc=b};this.setDeviceDataAnonymization=function(b){"boolean"!==typeof b?I("setDeviceDataAnonymization: The value for device data anonymization must be a boolean"):Ec=b};this.setEnableClientHints=function(b){"boolean"!==typeof b?I("[setEnableClientHints]: The value for enabling client hints must be a boolean"):Eb=b};bc.trigger("TrackerSetup",[this])}function zd(a,c){var e={},g,h;for(g=0;g<c.length;g++){var n=c[g];e[n]=1;for(h=0;h<a.length;h++)if(a[h]&&a[h][0]){var m=
a[h][0];n===m&&(Aa(a[h]),delete a[h],1<e[m]&&"addTracker"!==m&&"enableLinkTracking"!==m&&"setSecureCookie"!==m&&"enableCrossDomainLinking"!==m&&I("The method "+m+' is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Piwik trackers documentation'),e[m]++)}}Aa(["setVisitorIdCookie"])}function cd(a,c){var e=new zb(a,c);S.push(e);var g=window._paq.splice(0,window._paq.length),h=sd(g,dd,Ad),n=h.toApplySecond;g=h.toApplyLast;zd(h.toApplyFirst,
dd);for(h=0;h<n.length;h++)Aa(n[h]);n=window._paq;for(h=0;h<n.length;h++)Aa(n[h]);for(n=0;n<g.length;n++)Aa(g[n]);if("number"===typeof window._paq.length){var m={push:Aa},p=new Date;window._paq=m;var u=setInterval(function(){6E4<new Date-p?clearInterval(u):window._paq!==m&&(I("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."),
clearInterval(u))},1E3)}else I("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/.");return e}function Bd(a,c,e,g){function h(m){try{if(window["piwik_"+m])return window["piwik_"+m]}catch(p){}}var n=window.Piwik.getTracker(e,c);n.setDocumentTitle(a);n.setCustomData(g);(a=h("tracker_pause"))&&
n.setLinkTrackingTimer(a);(a=h("download_extensions"))&&n.setDownloadExtensions(a);(a=h("hosts_alias"))&&n.setDomains(a);(a=h("ignore_classes"))&&n.setIgnoreClasses(a);n.setTimingDataSamplingOnPageLoad(0);n.trackPageView();h("install_tracker")&&(window.piwik_track=function(m,p,u,v){n.setSiteId(p);n.setTrackerUrl(u);n.trackLink(m,v)},n.enableLinkTracking())}var qb={exports:{}},Va={exports:{}},gd=Va.exports,dc,Cd=qb.exports,ed,yd=function(a){return a&&a.__esModule&&Object.prototype.hasOwnProperty.call(a,
"default")?a["default"]:a}(function(){if(ed)return qb.exports;ed=1;(function(a,c){(function(e,g){a.exports=g(fd())})(Cd,function(e){var g=/(^|@)\S+:\d+/,h=/^\s*at .*(\S+:\d+|\(native\))/m,n=/^(eval@)?(\[native code])?$/;return{parse:function(m){if("undefined"!==typeof m.stacktrace||"undefined"!==typeof m["opera#sourceloc"])return this.parseOpera(m);if(m.stack&&m.stack.match(h))return this.parseV8OrIE(m);if(m.stack)return this.parseFFOrSafari(m);throw Error("Cannot parse given Error object");},extractLocation:function(m){if(-1===
m.indexOf(":"))return[m];m=/(.+?)(?::(\d+))?(?::(\d+))?$/.exec(m.replace(/[()]/g,""));return[m[1],m[2]||void 0,m[3]||void 0]},parseV8OrIE:function(m){return m.stack.split("\n").filter(function(p){return!!p.match(h)},this).map(function(p){-1<p.indexOf("(eval ")&&(p=p.replace(/eval code/g,"eval").replace(/(\(eval at [^()]*)|(,.*$)/g,""));var u=p.replace(/^\s+/,"").replace(/\(eval code/g,"(").replace(/^.*?\s+/,""),v=u.match(/ (\(.+\)$)/);u=v?u.replace(v[0],""):u;var q=this.extractLocation(v?v[1]:u);
u=v&&u||void 0;v=-1<["eval","<anonymous>"].indexOf(q[0])?void 0:q[0];return new e({functionName:u,fileName:v,lineNumber:q[1],columnNumber:q[2],source:p})},this)},parseFFOrSafari:function(m){return m.stack.split("\n").filter(function(p){return!p.match(n)},this).map(function(p){-1<p.indexOf(" > eval")&&(p=p.replace(/ line (\d+)(?: > eval line \d+)* > eval:\d+:\d+/g,":$1"));if(-1===p.indexOf("@")&&-1===p.indexOf(":"))return new e({functionName:p});var u=/((.*".+"[^@]*)?[^@]*)(?:@)/,v=p.match(u);v=v&&
v[1]?v[1]:void 0;u=this.extractLocation(p.replace(u,""));return new e({functionName:v,fileName:u[0],lineNumber:u[1],columnNumber:u[2],source:p})},this)},parseOpera:function(m){return!m.stacktrace||-1<m.message.indexOf("\n")&&m.message.split("\n").length>m.stacktrace.split("\n").length?this.parseOpera9(m):m.stack?this.parseOpera11(m):this.parseOpera10(m)},parseOpera9:function(m){var p=/Line (\d+).*script (?:in )?(\S+)/i;m=m.message.split("\n");for(var u=[],v=2,q=m.length;v<q;v+=2){var r=p.exec(m[v]);
r&&u.push(new e({fileName:r[2],lineNumber:r[1],source:m[v]}))}return u},parseOpera10:function(m){var p=/Line (\d+).*script (?:in )?(\S+)(?:: In function (\S+))?$/i;m=m.stacktrace.split("\n");for(var u=[],v=0,q=m.length;v<q;v+=2){var r=p.exec(m[v]);r&&u.push(new e({functionName:r[3]||void 0,fileName:r[2],lineNumber:r[1],source:m[v]}))}return u},parseOpera11:function(m){return m.stack.split("\n").filter(function(p){return!!p.match(g)&&!p.match(/^Error created at/)},this).map(function(p){var u=p.split("@"),
v=this.extractLocation(u.pop()),q=u.shift()||"";u=q.replace(/<anonymous function(: (\w+))?>/,"$2").replace(/\([^)]*\)/g,"")||void 0;var r;q.match(/\(([^)]*)\)/)&&(r=q.replace(/^[^(]+\(([^)]*)\)$/,"$1"));r=void 0===r||"[arguments not available]"===r?void 0:r.split(",");return new e({functionName:u,args:r,fileName:v[0],lineNumber:v[1],columnNumber:v[2],source:p})},this)}}})})(qb);return qb.exports}()),t={htmlCollectionToArray:function(a){var c=[],e;if(!a||!a.length)return c;for(e=0;e<a.length;e++)c.push(a[e]);
return c},find:function(a){if(!document.querySelectorAll||!a)return[];a=document.querySelectorAll(a);return t.htmlCollectionToArray(a)},findMultiple:function(a){if(!a||!a.length)return[];var c,e=[];for(c=0;c<a.length;c++){var g=t.find(a[c]);e=e.concat(g)}return e=t.makeNodesUnique(e)},findNodesByTagName:function(a,c){if(!a||!c||!a.getElementsByTagName)return[];var e=a.getElementsByTagName(c);return t.htmlCollectionToArray(e)},makeNodesUnique:function(a){var c=[].concat(a);a.sort(function(m,p){if(m===
p)return 0;var u=Y(c,m),v=Y(c,p);return u===v?0:u>v?-1:1});if(1>=a.length)return a;var e=0,g=0,h=[],n;for(n=a[e++];n;)n===a[e]&&(g=h.push(e)),n=a[e++]||null;for(;g--;)a.splice(h[g],1);return a},getAttributeValueFromNode:function(a,c){if(t.hasNodeAttribute(a,c)){if(a&&a.getAttribute)return a.getAttribute(c);if(a&&a.attributes&&"undefined"!==O(a.attributes[c])){if(a.attributes[c].value)return a.attributes[c].value;if(a.attributes[c].nodeValue)return a.attributes[c].nodeValue;var e,g=a.attributes;if(g){for(e=
0;e<g.length;e++)if(g[e].nodeName===c)return g[e].nodeValue;return null}}}},hasNodeAttributeWithValue:function(a,c){return!!t.getAttributeValueFromNode(a,c)},hasNodeAttribute:function(a,c){return a&&a.hasAttribute?a.hasAttribute(c):a&&a.attributes?"undefined"!==O(a.attributes[c]):!1},hasNodeCssClass:function(a,c){if(a&&c&&a.className){var e="string"===typeof a.className?a.className.split(" "):[];if(-1!==Y(e,c))return!0}return!1},findNodesHavingAttribute:function(a,c,e){e||(e=[]);if(!a||!c)return e;
a=hc(a);if(!a)return e;var g;for(g=0;g<a.length;g++){var h=a[g];t.hasNodeAttribute(h,c)&&e.push(h);e=t.findNodesHavingAttribute(h,c,e)}return e},findFirstNodeHavingAttribute:function(a,c){if(a&&c){if(t.hasNodeAttribute(a,c))return a;var e=t.findNodesHavingAttribute(a,c);if(e&&e.length)return e[0]}},findFirstNodeHavingAttributeWithValue:function(a,c){if(a&&c){if(t.hasNodeAttributeWithValue(a,c))return a;var e=t.findNodesHavingAttribute(a,c);if(e&&e.length){var g;for(g=0;g<e.length;g++)if(t.getAttributeValueFromNode(e[g],
c))return e[g]}}},findNodesHavingCssClass:function(a,c,e){e||(e=[]);if(!a||!c)return e;if(a.getElementsByClassName)return c=a.getElementsByClassName(c),t.htmlCollectionToArray(c);a=hc(a);if(!a)return[];var g;for(g=0;g<a.length;g++){var h=a[g];t.hasNodeCssClass(h,c)&&e.push(h);e=t.findNodesHavingCssClass(h,c,e)}return e},findFirstNodeHavingClass:function(a,c){if(a&&c){if(t.hasNodeCssClass(a,c))return a;var e=t.findNodesHavingCssClass(a,c);if(e&&e.length)return e[0]}},isLinkElement:function(a){if(!a)return!1;
a=String(a.nodeName).toLowerCase();return-1!==Y(["a","area"],a)},setAnyAttribute:function(a,c,e){a&&c&&(a.setAttribute?a.setAttribute(c,e):a[c]=e)}},jd=/^[a-z]+:\/\/.+$/i,Dd={model:"ch_m",brands:"ch_b",platform:"ch_p",platformVersion:"ch_pv",fullVersionList:"ch_fvl"},xc=function(a){if("object"!==O(a))return"";var c="",e;for(e in a){var g=Dd[e],h=a[e];if(g&&h){g="&".concat(g,"=");var n=g.concat;h?(h="object"===O(h)?JSON.stringify(h):h,h=window.encodeURIComponent(h)):h="";c+=n.call(g,h)}}return c},
oc=[15,30,60,120,240,480,960,1800],ra={PeriodicHeartbeat:1,LastHeartbeat:2,BlurHeartbeat:3},xb=Object.freeze({pdf:"application/pdf",qt:"video/quicktime",realp:"audio/x-pn-realaudio-plugin",wma:"application/x-mplayer2",dir:"application/x-director",fla:"application/x-shockwave-flash",java:"application/x-java-vm",gears:"application/x-googlegears",ag:"application/x-silverlight"}),ab,ea={},B=document,sa=navigator,A=window,Hc=!1,G=A.encodeURIComponent,xd=A.decodeURIComponent,S=[],cc=[],D={CONTENT_ATTR:"data-track-content",
CONTENT_CLASS:"piwikTrackContent",CONTENT_NAME_ATTR:"data-content-name",CONTENT_PIECE_ATTR:"data-content-piece",CONTENT_PIECE_CLASS:"piwikContentPiece",CONTENT_TARGET_ATTR:"data-content-target",CONTENT_TARGET_CLASS:"piwikContentTarget",CONTENT_IGNOREINTERACTION_ATTR:"data-content-ignoreinteraction",CONTENT_IGNOREINTERACTION_CLASS:"piwikContentIgnoreInteraction",CONTENT_WATCHED_ATTR:"data-content-watched",location:void 0,findContentNodes:function(){return t.findMultiple(["."+this.CONTENT_CLASS,"["+
this.CONTENT_ATTR+"]"])},findContentNodesWithinNode:function(a){if(!a)return[];var c=t.findNodesHavingCssClass(a,this.CONTENT_CLASS),e=t.findNodesHavingAttribute(a,this.CONTENT_ATTR);if(e&&e.length){var g;for(g=0;g<e.length;g++)c.push(e[g])}t.hasNodeAttribute(a,this.CONTENT_ATTR)?c.push(a):t.hasNodeCssClass(a,this.CONTENT_CLASS)&&c.push(a);return c=t.makeNodesUnique(c)},findParentContentNode:function(a){if(a)for(var c=0;a&&a!==B&&a.parentNode;){if(t.hasNodeAttribute(a,this.CONTENT_ATTR)||t.hasNodeCssClass(a,
this.CONTENT_CLASS))return a;a=a.parentNode;if(1E3<c)break;c++}},findPieceNode:function(a){var c;(c=t.findFirstNodeHavingAttribute(a,this.CONTENT_PIECE_ATTR))||(c=t.findFirstNodeHavingClass(a,this.CONTENT_PIECE_CLASS));return c?c:a},findTargetNodeNoDefault:function(a){if(a){var c=t.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_TARGET_ATTR);if(c||(c=t.findFirstNodeHavingAttribute(a,this.CONTENT_TARGET_ATTR))||(c=t.findFirstNodeHavingClass(a,this.CONTENT_TARGET_CLASS)))return c}},findTargetNode:function(a){var c=
this.findTargetNodeNoDefault(a);return c?c:a},findTargetNodesNoDefault:function(a){if(a){var c=t.findNodesHavingAttribute(a,this.CONTENT_TARGET_ATTR);if(c&&0<c.length||(c=t.findNodesHavingCssClass(a,this.CONTENT_TARGET_CLASS))&&0<c.length)return c}},findTargetNodes:function(a){var c=D.findTargetNodesNoDefault(a);return c&&0<c.length?c:[a]},findContentName:function(a){if(a){var c=t.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_NAME_ATTR);if(c)return t.getAttributeValueFromNode(c,this.CONTENT_NAME_ATTR);
if(c=this.findContentPiece(a))return this.removeDomainIfIsInLink(c);if(t.hasNodeAttributeWithValue(a,"title"))return t.getAttributeValueFromNode(a,"title");c=this.findPieceNode(a);if(t.hasNodeAttributeWithValue(c,"title"))return t.getAttributeValueFromNode(c,"title");a=this.findTargetNode(a);if(t.hasNodeAttributeWithValue(a,"title"))return t.getAttributeValueFromNode(a,"title")}},findContentPiece:function(a){if(a){var c=t.findFirstNodeHavingAttributeWithValue(a,this.CONTENT_PIECE_ATTR);if(c)return t.getAttributeValueFromNode(c,
this.CONTENT_PIECE_ATTR);a=this.findPieceNode(a);if(a=this.findMediaUrlInNode(a))return this.toAbsoluteUrl(a)}},findContentTarget:function(a){if(a){var c=this.findTargetNode(a);if(t.hasNodeAttributeWithValue(c,this.CONTENT_TARGET_ATTR))return t.getAttributeValueFromNode(c,this.CONTENT_TARGET_ATTR);if(t.hasNodeAttributeWithValue(c,"href"))return a=t.getAttributeValueFromNode(c,"href"),this.toAbsoluteUrl(a);a=this.findPieceNode(a);if(t.hasNodeAttributeWithValue(a,"href"))return a=t.getAttributeValueFromNode(a,
"href"),this.toAbsoluteUrl(a)}},isSameDomain:function(a){if(!a||!a.indexOf)return!1;if(0===a.indexOf(this.getLocation().origin))return!0;a=a.indexOf(this.getLocation().host);return 8>=a&&0<=a?!0:!1},removeDomainIfIsInLink:function(a){a&&a.search&&-1!==a.search(/^https?:\/\/[^/]+/)&&this.isSameDomain(a)&&((a=a.replace(/^.*\/\/[^/]+/,""))||(a="/"));return a},findMediaUrlInNode:function(a){if(a){var c=a.nodeName.toLowerCase();if(-1!==Y(["img","embed","video","audio"],c)&&t.findFirstNodeHavingAttributeWithValue(a,
"src"))return a=t.findFirstNodeHavingAttributeWithValue(a,"src"),t.getAttributeValueFromNode(a,"src");if("object"===c&&t.hasNodeAttributeWithValue(a,"data"))return t.getAttributeValueFromNode(a,"data");if("object"===c){if((c=t.findNodesByTagName(a,"param"))&&c.length){var e;for(e=0;e<c.length;e++)if("movie"===t.getAttributeValueFromNode(c[e],"name")&&t.hasNodeAttributeWithValue(c[e],"value"))return t.getAttributeValueFromNode(c[e],"value")}if((a=t.findNodesByTagName(a,"embed"))&&a.length)return this.findMediaUrlInNode(a[0])}}},
trim:function(a){return ca(a)},isOrWasNodeInViewport:function(a){if(!a||!a.getBoundingClientRect||1!==a.nodeType)return!0;var c=a.getBoundingClientRect(),e=B.documentElement||{},g=0>c.top;g&&a.offsetTop&&(g=0<a.offsetTop+c.height);a=e.clientWidth;A.innerWidth&&a>A.innerWidth&&(a=A.innerWidth);e=e.clientHeight;A.innerHeight&&e>A.innerHeight&&(e=A.innerHeight);return(0<c.bottom||g)&&0<c.right&&c.left<a&&(c.top<e||g)},isNodeVisible:function(a){var c=yb(a);a=this.isOrWasNodeInViewport(a);return c&&a},
buildInteractionRequestParams:function(a,c,e,g){var h="";a&&(h+="c_i="+G(a));c&&(h&&(h+="&"),h+="c_n="+G(c));e&&(h&&(h+="&"),h+="c_p="+G(e));g&&(h&&(h+="&"),h+="c_t="+G(g));return h},buildImpressionRequestParams:function(a,c,e){a="c_n="+G(a)+"&c_p="+G(c);e&&(a+="&c_t="+G(e));return a},buildContentBlock:function(a){if(a){var c=this.findContentName(a),e=this.findContentPiece(a);a=this.findContentTarget(a);c=this.trim(c);e=this.trim(e);a=this.trim(a);return{name:c||"Unknown",piece:e||"Unknown",target:a||
""}}},collectContent:function(a){if(!a||!a.length)return[];var c=[],e;for(e=0;e<a.length;e++){var g=this.buildContentBlock(a[e]);w(g)&&c.push(g)}return c},setLocation:function(a){this.location=a},getLocation:function(){var a=this.location||A.location;a.origin||(a.origin=a.protocol+"//"+a.hostname+(a.port?":"+a.port:""));return a},toAbsoluteUrl:function(a){return a&&String(a)===a||""===a?""===a?this.getLocation().href:-1!==a.search(/^\/\//)?this.getLocation().protocol+a:-1!==a.search(/:\/\//)?a:0===
a.indexOf("#")||0===a.indexOf("?")?this.getLocation().origin+this.getLocation().pathname+a:0===a.search("^[a-zA-Z]{2,11}:")?a:-1!==a.search(/^\//)?this.getLocation().origin+a:this.getLocation().origin+this.getLocation().pathname.match(/(.*\/)/)[0]+a:a},isUrlToCurrentDomain:function(a){a=this.toAbsoluteUrl(a);if(!a)return!1;var c=this.getLocation().origin;return c===a?!0:0===String(a).indexOf(c)?":"===String(a).substr(c.length,1)?!1:!0:!1},setHrefAttribute:function(a,c){a&&c&&t.setAnyAttribute(a,"href",
c)},shouldIgnoreInteraction:function(a){var c=t.hasNodeAttribute(a,this.CONTENT_IGNOREINTERACTION_ATTR);a=t.hasNodeCssClass(a,this.CONTENT_IGNOREINTERACTION_CLASS);return c||a}},dd="addTracker setTrackingSourceProvider disableCookies enableCookies setSessionIdStrictPrivacyMode setTrackerUrl setAPIUrl enableCrossDomainLinking setCrossDomainLinkingTimeout customCrossDomainLinkDecorator customCrossDomainLinkVisitorIdGetter setSecureCookie setCookiePath setCookieDomain setDomains setUserId setSiteInspectorSetup setSiteId enableLinkTracking setCustomVariableMaximumLength setDeviceDataAnonymization setEnableClientHints".split(" "),
Ad=["trackError"];V(A,"beforeunload",function(){for(var a=S,c=ab,e=0;e<a.length;e+=1)a[e].trackHeartBeat({lastHeartbeat:!0});for(a=0;a<cc.length;a+=1)cc[a].trackHeartBeat({lastHeartbeat:!0});if(c){do a=new Date;while(a.getTime()<c)}},!1);var bc={initialized:!1,JSON:JSON,DOM:{addEventListener:function(a,c,e,g){"undefined"===O(g)&&(g=!1);V(a,c,e,g)},onLoad:Ba,onReady:Oa,isNodeVisible:yb,isOrWasNodeVisible:D.isNodeVisible},on:function(a,c){ea[a]||(ea[a]=[]);ea[a].push(c)},off:function(a,c){if(ea[a]){var e=
0;for(e;e<ea[a].length;e++)ea[a][e]===c&&ea[a].splice(e,1)}},trigger:function(a,c,e){if(ea[a]){var g=0;for(g;g<ea[a].length;g++)ea[a][g].apply(e||A,c)}},getTracker:function(a,c){w(c)||(c=this.getAsyncTracker().getSiteId());w(a)||(a=this.getAsyncTracker().getTrackerUrl());var e=new zb(a,c);cc.push(e);return e},getAsyncTrackers:function(){return S},addTracker:function(a,c){return S.length?S[0].addTracker(a,c):cd(a,c)},getAsyncTracker:function(a,c){if(S&&S.length&&S[0])var e=S[0];else return cd(a,c);
if(!c&&!a)return e;w(c)&&null!==c||!e||(c=e.getSiteId());w(a)&&null!==a||!e||(a=e.getTrackerUrl());var g=0;for(g;g<S.length;g++)if((e=S[g])&&String(e.getSiteId())===String(c)&&e.getTrackerUrl()===a)return e}};"function"===typeof define&&define.amd&&define("piwik",[],function(){return bc});var Ed=bc;"object"!==O(window._paq)&&(window._paq=[]);"object"!==O(window.Piwik)&&(window.Piwik=Ed);(function(){if(window&&"object"===O(window.piwikPluginAsyncInit)&&window.piwikPluginAsyncInit.length){var a=0;for(a;a<
window.piwikPluginAsyncInit.length;a++)if("function"===typeof window.piwikPluginAsyncInit[a])window.piwikPluginAsyncInit[a]()}window&&window.piwikAsyncInit&&window.piwikAsyncInit();window.Piwik.getAsyncTrackers().length?I("Matomo javascript tracker or Piwik PRO javascript tracker was already initiated on this page. Please check the tracker setup. Matomo conflict can be resolved using these instructions: https://help.piwik.pro/support/questions/can-i-use-piwik-pro-and-matomo-at-the-same-time/."):("object"!==
O(window._paq)||"undefined"===O(window._paq.length)?0:window._paq.length)?window.Piwik.addTracker():window._paq={push:function(c){I("_paq.push() was used but Piwik tracker was not initialized before the ppms.js file was loaded. Make sure to configure the tracker via _paq.push before loading ppms.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order.")}};window.Piwik.trigger("PiwikInitialized",
[]);window.Piwik.initialized=!0})();"undefined"===O(window.AnalyticsTracker)&&(window.AnalyticsTracker=window.Piwik);"function"!==typeof window.piwik_log&&(window.piwik_log=Bd)})()
//# sourceMappingURL=ppms.js.map
